if (NOT DEFINED EDGE_MESSAGE_COLORS)
	set(EDGE_MESSAGE_COLORS)

	string(ASCII 27 Esc)
	set(EDGE_COLOUR_RESET		"${Esc}[m")
	set(EDGE_COLOUR_BOLD		"${Esc}[1m")
	set(EDGE_COLOUR_RED			"${Esc}[31m")
	set(EDGE_COLOUR_GREEN		"${Esc}[32m")
	set(EDGE_COLOUR_YELLOW		"${Esc}[33m")
	set(EDGE_COLOUR_BLUE 		"${Esc}[34m")
	set(EDGE_COLOUR_MAGENTA		"${Esc}[35m")
	set(EDGE_COLOUR_CYAN		"${Esc}[36m")
	set(EDGE_COLOUR_WHITE		"${Esc}[37m")
endif()